# Generated by Django 6.0 on 2026-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0002_waterbill_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
