# Generated by Django 6.0 on 2026-01-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0003_waterbill_total_amount'),
    ]

    operations = [
    ]
