# Generated by Django 6.0 on 2026-01-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0004_auto_20260127_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='fixed_service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
