# Generated by Django 6.0 on 2026-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0005_waterbill_fixed_service_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
    ]
