# Generated by Django 6.0 on 2026-02-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0006_alter_waterbill_rate_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbill',
            name='total_amount',
        ),
    ]
