# Generated by Django 6.0 on 2026-02-03 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0007_remove_waterbill_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
