# Generated by Django 6.0 on 2026-02-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0008_waterbill_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='billing_period',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
