# Generated by Django 6.0 on 2026-02-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_billing', '0009_waterbill_billing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='billing_period',
            field=models.DateField(),
        ),
    ]
