"""
Django settings for waterbill project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # Import to load .env file

# Load environment variables from .env file
load_dotenv()

 # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# 3. Use os.getenv to pull the values
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'


# This allows laptop and phone to see the site
# Clean this up to just one line
ALLOWED_HOSTS = ['utilitybill.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # THIS IS TO AUTOMATICALLY FORMAT NUMBERS
    'django.contrib.humanize',

    'water_billing', #this is my app now
    'electric_billing', #electric billing app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'waterbill.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # this is for the summarry
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'waterbill.wsgi.application'


# Database in mySQL Workbench
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


 

# Tell Django to use  custom /login/ path instead of the default /accounts/login/
LOGIN_URL = 'login'  # Points to path('login/', ..., name='login')
LOGIN_REDIRECT_URL = 'billing_summary' # Go to the main dashboard after login
LOGOUT_REDIRECT_URL = 'login'  # Go to login page after logout

LOGOUT_ON_GET = True

# Session expires when the user closes the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Session lasts for only 30 minutes of inactivity (optional)
SESSION_COOKIE_AGE = 1800 

# Ensures the session is saved on every request
SESSION_SAVE_EVERY_REQUEST = True

 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# This tells Django to look in  C:\Users\AdminPC\Desktop\waterbill\static folder
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# During development, print emails to the console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Later, when  go live with Gmail, this  will change  to:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'




# This ensures Django can find users by email
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# This is the "From" address to clients will see
DEFAULT_FROM_EMAIL = 'Water Bill Support <noreply@yourdomain.com>'


