# Generated by Django 6.0 on 2026-01-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('billing_date', models.DateField()),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kwh', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('fixed_service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
