# Generated by Django 6.0 on 2026-01-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricbill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
