# Generated by Django 6.0 on 2026-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_billing', '0002_electricbill_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
