# Generated by Django 6.0 on 2026-01-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_billing', '0003_electricbill_total_amount'),
    ]

    operations = [
    ]
