# Generated by Django 6.0 on 2026-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_billing', '0004_auto_20260127_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbill',
            name='fixed_service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='electricbill',
            name='rate_per_kwh',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=10),
        ),
    ]
