# Generated by Django 6.0 on 2026-02-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_billing', '0005_alter_electricbill_fixed_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricbill',
            name='billing_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
