# Generated by Django 6.0 on 2026-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_billing', '0006_electricbill_billing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbill',
            name='billing_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
