# Generated by Django 6.0 on 2026-02-05 23:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_billing', '0008_electricbill_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbill',
            name='rate_per_kwh',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.65'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='electricbill',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
    ]
